### ISSUE TITLE
Support for posts in additional PowerShell Discord Servers

### ISSUE THREAD

**Issue by TechDufus** [powershelllive/TwitchStreamNotifcations#25]
It would be nice for Discord servers to also 'opt-in' to getting the automated streaming posts in a #Streaming channel.

Any initial thoughts on something like this?

**Comment by TechDufus** [comment]
Message is sent here: https://github.com/powershelllive/TwitchStreamNotifcations/blob/76b82620aaa886866a06fe623d17f85e3fccacf9/src/functions/DiscordEventHandler.cs#L50

But it looks like it's referencing an environment variable, which we could make an array of webhooks: 
https://github.com/powershelllive/TwitchStreamNotifcations/blob/76b82620aaa886866a06fe623d17f85e3fccacf9/config/main.parameters.json#L34
https://github.com/powershelllive/TwitchStreamNotifcations/blob/76b82620aaa886866a06fe623d17f85e3fccacf9/src/utilities/DiscordClient.cs#L18

Knowing that, I'd say we add a loop to the [DiscordClient.cs](https://github.com/powershelllive/TwitchStreamNotifcations/blob/76b82620aaa886866a06fe623d17f85e3fccacf9/src/utilities/DiscordClient.cs) which would send multiple httpResponses.

Am I on the right track? New to C#.. 😂

**Comment by SimonWahlin** [comment]
Yea you are probably on the right track but that would mean we had to maintain a set of webhooks in the keyvault. Those are secret and the problem I see is not how to send messages to the other servers but rather how to have the servers securely hand us the webhook uris and for us to maintain them.

If you have a server where you want the same notifications, just deploy your own function app, it's fairly straight forward and almost free.
